### ISSUE TITLE
Request license adjustment or permission to adapt/reuse

### ISSUE THREAD

**Issue by ConnectedSystems** [amacd31/gr4j#2]
Hello,

Thanks for writing up this package.

I'm developing a package in Julia, [Streamfall](https://github.com/ConnectedSystems/Streamfall.jl), and adapted your code for it.

I'd like to credit you in the documentation but wonder if this falls foul of the license terms:

"The name of the author may not be used to endorse or promote products derived from this software without specific prior written permission."

Could I ask that the code be re-released under the MIT (or similar) license?

Alternatively, could I have your permission to include the adapted code with the following statement in the relevant file?

> Portions of the GR4J implementation is directly adapted from Python code written by Andrew MacDonald (2014).
> 
> Per license requirements, the full license conditions included below.
> 
> [Your current license text]

Thanks again

**Comment by amacd31** [comment]
Hey, glad you found this package useful.

My understanding is the first two clauses of the 3-clause BSD license is equivalent to the MIT license. The third clause is about endorsement/promotion rather than requiring written permission for crediting use of the code. For example, saying "Streamfall developed in part by Andrew MacDonald" would imply endorsement and require my permission, while the text you have proposed does not imply endorsement and wouldn't require my approval.

Including the statement you suggest would certainly meet the requirements of the license.

In case you hadn't spotted the data used as an input to the tests here were derived from public domain data and are not under the same license as the rest of the repository. You can find more about the data used here: https://github.com/amacd31/daily_hydromet_sample_data (in case that is of interest).

All the best for your project and let me know if you have any other questions on this.
