### ISSUE TITLE
the function used to calculate perc may be not right?

### ISSUE THREAD

**Issue by HydroCW** [amacd31/gr4j#3]
It seems that the the function used to calculate perc is not the same as discribed in the model paper?

**Comment by amacd31** [comment]
Hi @HydroCW, by "calculate perc" are you referring to equation 6 in the Perrin et al. paper? Which would be line [102](https://github.com/amacd31/gr4j/blob/master/gr4j/gr4j.py#L102) of the Python code here.

It has been a long time since I've looked at this code and it isn't obvious to me how I got from that equation to this code. I do recall working on trying to modify the math in a way that improved computation (mostly by switching division for multiplication where possible). Unfortunately the jupyter notebooks I used when validating the math and doing performance testing were most likely lost in a hard drive failure a number of years back (in hindsight they probably should have been included as reference materials in this repo).

Did you close this because you were able to identify that the math does line up with the code?
